SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR amd64)

SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

SET(CLANG_TARGET_TRIPLE x86_64-linux-gnu)

SET(CMAKE_C_COMPILER clang)
SET(CMAKE_C_COMPILER_TARGET ${CLANG_TARGET_TRIPLE})
SET(CMAKE_CXX_COMPILER clang++)
SET(CMAKE_CXX_COMPILER_TARGET ${CLANG_TARGET_TRIPLE})

SET(CMAKE_FIND_ROOT_PATH /usr/lib/x86_64-linux-gnu/)
SET(ONLY_CMAKE_FIND_ROOT_PATH TRUE)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CMAKE_PREFIX_PATH /usr/lib/x86_64-linux-gnu/cmake/)
