SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR amd64)

SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

SET(CLANG_TARGET_TRIPLE x86_64-linux-gnu)

SET(CMAKE_C_COMPILER clang)
SET(CMAKE_C_COMPILER_TARGET ${CLANG_TARGET_TRIPLE})
SET(CMAKE_CXX_COMPILER clang++)
SET(CMAKE_CXX_COMPILER_TARGET ${CLANG_TARGET_TRIPLE})

SET(CMAKE_LIBRARY_ARCHITECTURE x86_64-linux-gnu)
